categories_file: categories.json
data_dir: data
email:
  app_password: jdyn bntb qljz wkgi
  recipient: bgnissen@gmail.com
  smtp_host: smtp.gmail.com
  smtp_port: 587
  username: bgnissen@gmail.com
google_drive:
  folder_id: '1LrQJpjLpt8rCdnyJG4BRHNnBcNmME7Hb'
  processed_folder_name: processed
  service_account_file: config/service_account.json
gui:
  password: changeme
  port: 5000
  secret_key: change-this-to-something-random
notion:
  database_id: 3103379e-f16a-8155-aedc-d69e17d727d8
  token: ''  # set your Notion API token here
pocketbase:
  url: 'http://locserv.tail18bcbb.ts.net:8091'
  email: 'banking@mybank.local'
  password: 'Banking#Q-CsEdIGYdvDxx0X'
poll_interval_minutes: 15
